version: "3"

services:
  web:
    build: .
    image: ${IMAGE_NAME}:v1
    container_name: ${CONTAINER_NAME}
    command: python main.py
    ports:
      - ${PORT}:${PORT2}
    volumes:
      - ./:/app