version: '3.1'

services:

  bot:
    build: .
    restart: always
    entrypoint:
      - ./bin/entrypoint.sh
    depends_on:
      - postgres
    image: ${IMAGE_NAME}:v1
    container_name: ${CONTAINER_NAME}
    environment:
      ADMINS: ${ADMINS}
      BOT_TOKEN: ${BOT_TOKEN}
      RATE_LIMIT: ${RATE_LIMIT:-0.5}

      DATABASE_USER: ${DB_USER}
      DATABASE_PASS: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}

      DATABASE_NAME: ${DB_NAME}

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: