from .language import get_language_inline_markup
from .calendar import get_calendar_inline_markup
from .task import get_add_file_inline_markup, get_finish_add_files_inline_markup, get_edit_file_inline_markup, get_yes_no_inline_markup, get_upload_files_inline_markup, get_todo_inline_markup, get_completed_inline_markup, get_edit_task_markup, get_delete_all_markup